AWSTemplateFormatVersion: "2010-09-09"
Description: SonarQube EC2 instance
Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html
  MyEC2Instance: #An inline comment
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-2f726546"  #Linux AMI
      instanceType: t2.micro
      # KeyName: devops
      # - DeviceName: /dev/sdm
      #   Ebs:
      #     VolumeSize: 8
    # BlockDeviceMappings:
    #   - DeviceName: /dev/sda1
    #     Ebs:
    #       #VolumeType: io1
    #       #VolumeType: gp2
    #       #Iops: 200
    #       #DeleteOnTermation: true
    #       VolumeSize: 40
    #   - DeviceName: /dev/sdm
    #     Ebs:
    #       #VolumeType: io1
    #       #VolumeType: gp2
    #       #Iops: 200
    #       #DeleteOnTermation: false
    #       VolumeSize: 8